name: Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run lint:types
      - run: npm run test

  deploy:
    needs: lint
    runs-on: ubuntu-latest
    concurrency:
      group: staging
      cancel-in-progress: true
    steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.STAGING_SSH_HOST}} # Remote server address / ip - required
          user: ${{secrets.STAGING_SSH_USER}} # Remote server user - required
          private_key: ${{secrets.STAGING_SSH_PRIVATE_KEY}} # Private ssh key registered on the remote server - required
          host_fingerprint: ${{secrets.STAGING_SSH_FINGERPRINT}} # Public ssh key fingerprint, viewable via ssh-keyscan -H $HOST -p $PORT - optional
          command: source ~/.nvm/nvm.sh; ~/deploy.sh
